export const CATEGORIES: { [key: string]: string[] } = {
  'Arts & entertainment': [
    'Art',
    'Music',
    'Theater',
    'Aesthetics',
    'Education',
    'Entertainment',
    'Film',
    'Photography',
    'Television',
    'Video Games',
  ],
  'Biographies & memoirs': [
    'Biography',
    'Memoir',
    'Autobiography',
    'Juvenile Nonfiction',
    'Biographies',
  ],
  'Business & investing': [
    'Business',
    'Investing',
    'Economics',
    'Finance',
    'Management',
    'Marketing',
    'Personal Finance',
  ],
  "Children's books": [
    'Children',
    'Juvenile Fiction',
    'Juvenile Nonfiction',
    'Picture Books',
    'Literary Criticism',
  ],
  'Computers & Technology': [
    'Computers',
    'Technology',
    'Computer Science',
    'Information Technology',
    'Internet',
    'Programming',
    'Software',
    'Web Development',
    'Technology & Engineering',
  ],
  'Fiction & literature': [
    'Fiction',
    'Literature',
    'Classics',
    'Historical Fiction',
    'Literary Collections',
    'Poetry',
    'Short Stories',
    'Social Science',
  ],
  'Health, mind & body': [
    'Health',
    'Mind',
    'Body',
    'Fitness',
    'Nutrition',
    'Self-Help',
    'Christian Science',
    'Family & Relationships',
    'Psychology',
  ],
  'Mystery & thrillers': [
    'Mystery',
    'Thriller',
    'Detective and mystery stories, English',
    'Suspense fiction',
    'Crime fiction',
  ],
  'Religion & Spirituality': [
    'Religion',
    'Spirituality',
    'Christianity',
    'Buddhism',
    'Hinduism',
    'Islam',
    'Judaism',
    'New Age',
    'Occult',
    'Philosophy',
    'Theology',
    'Body, Mind & Spirit',
    'History',
  ],
  'Romance': [
    'Romance',
    'Love stories',
    'Romantic suspense fiction',
    'Boys',
    "Children's stories",
    'Christian fiction',
    'Fiction',
  ],
  'Science fiction & fantasy': [
    'Science Fiction',
    'Fantasy',
    'Literary Criticism',
    'Science Fiction & Fantasy',
    'Science Fiction, Fantasy, Magic',
    'Science Fiction, Fantasy, & Magic',
    'Philosophy',
    'Technology & Engineering',
  ],
  'Law': [
    'Law',
    'Political Science',
    'Comparative government',
    'Constitutional law',
    'International law',
    'Jurisprudence',
    'Legal stories',
    'Political Science',
    'Public law',
    'History',
  ],
};
