version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - lms-network

  lmsapp:
    build:
      context: .
      dockerfile: lms-server/Dockerfile
    container_name: lmsapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LmsDbConnectionString=Server=sqlserver,1433;Database=LmsDatabase;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;Encrypt=False;
   
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - lms-network

volumes:
  sqlserver-data:

networks:
  lms-network:
    driver: bridge